### ISSUE TITLE
Manually annotating correctly predicted triples with template labels

### ISSUE THREAD

**Issue by adaruna3** [dair-iitd/OxKBC#2]
Hi all,

Your paper is very interesting to me, and I am planning to use your method in some research for robotics. I have a few different prior works applying KGE models to robotics problems. I am now working on a final project for my PhD that involves explainability and HRI.

So far I have been able to run most of the steps in the README of the repo with my robotics dataset. However, I was not clear on how to manually label correctly predicted triples (i.e. Hits@1) with the "the template producing
the best explanation", as written in your paper. Since the model to produce the explanations is not available during annotation, how did you do the labeling? 

One guess I have is manually looking at triple paths in the KB and selecting from those, but that does seem rather time consuming. Another is calculating the highest scoring explanation path according to "Compatibility" as defined in page 9 for each template, then selecting among those 5 explanations paths plus no explanation.

I would really appreciate your advice on this and thanks for open-sourcing this great research!
Best ~ Angel

**Comment by adaruna3** [comment]
After looking through the codebase more, it seems like the file to use for this purpose might be `get_exp_table.py` which would be inline with the second method I mentioned. Your feedback would still be much appreciated to confirm. Thanks!

**Comment by ynandwan** [comment]
We first generate the highest-scoring explanation from each template and a human annotator would then select either the best one amongst them or 'no explanation' when none of them is plausible. So your second method is spot on.

Best,
Yatin

**Comment by adaruna3** [comment]
Hi Yatin,

Great. I got some output that I can interpret with `get_html_explanations.py`. Thanks for the info!

Best ~ Angel
